use std::{collections::HashMap, fmt};
const MAGIC:&[u8;8]=b"SENSEIDX";const VERSION:u16=2;
#[derive(Clone,Copy,Debug,PartialEq,Eq)]pub enum MediaType{Other=0,Movie=1,Series=2}
impl MediaType{fn from_code(c:u8)->Self{match c{1=>Self::Movie,2=>Self::Series,_=>Self::Other}}}
#[derive(Clone,Debug)]pub struct QuantizedItem{pub id:String,pub name:String,pub media_type:MediaType,pub vector:Vec<i8>}
#[derive(Clone,Debug)]pub struct RecommendationHit{pub id:String,pub name:String,pub media_type:MediaType,pub score:f32}
#[derive(Clone,Debug)]pub struct SenseIndex{dimensions:usize,items:Vec<QuantizedItem>,positions:HashMap<String,usize>}
#[derive(Clone,Debug)]pub enum IndexError{Truncated,BadMagic,UnsupportedVersion(u16),InvalidDimensions,InvalidUtf8,DuplicateId(String),TrailingBytes}
impl fmt::Display for IndexError{fn fmt(&self,f:&mut fmt::Formatter<'_>)->fmt::Result{write!(f,"{self:?}")}}
impl std::error::Error for IndexError{}
fn u16le(b:&[u8],c:&mut usize)->Result<u16,IndexError>{let e=c.checked_add(2).ok_or(IndexError::Truncated)?;let r:[u8;2]=b.get(*c..e).ok_or(IndexError::Truncated)?.try_into().map_err(|_|IndexError::Truncated)?;*c=e;Ok(u16::from_le_bytes(r))}
fn u32le(b:&[u8],c:&mut usize)->Result<u32,IndexError>{let e=c.checked_add(4).ok_or(IndexError::Truncated)?;let r:[u8;4]=b.get(*c..e).ok_or(IndexError::Truncated)?.try_into().map_err(|_|IndexError::Truncated)?;*c=e;Ok(u32::from_le_bytes(r))}
fn cos(a:&[i8],b:&[i8])->f32{if a.is_empty()||a.len()!=b.len(){return 0.0}let(mut d,mut aa,mut bb)=(0i64,0i64,0i64);for(&x,&y)in a.iter().zip(b){let(x,y)=(x as i64,y as i64);d+=x*y;aa+=x*x;bb+=y*y}if aa==0||bb==0{0.0}else{d as f32/((aa as f32).sqrt()*(bb as f32).sqrt())}}
impl SenseIndex{
pub fn from_bytes(b:&[u8])->Result<Self,IndexError>{if b.len()<8||&b[..8]!=MAGIC{return Err(IndexError::BadMagic)}let mut c=8;let v=u16le(b,&mut c)?;if v!=VERSION{return Err(IndexError::UnsupportedVersion(v))}let dim=u16le(b,&mut c)? as usize;if dim==0{return Err(IndexError::InvalidDimensions)}let n=u32le(b,&mut c)? as usize;let mut items=Vec::with_capacity(n);let mut pos=HashMap::with_capacity(n);for i in 0..n{let l=u16le(b,&mut c)? as usize;let e=c.checked_add(l).ok_or(IndexError::Truncated)?;let id=std::str::from_utf8(b.get(c..e).ok_or(IndexError::Truncated)?).map_err(|_|IndexError::InvalidUtf8)?.to_owned();c=e;if pos.insert(id.clone(),i).is_some(){return Err(IndexError::DuplicateId(id))}let mt=MediaType::from_code(*b.get(c).ok_or(IndexError::Truncated)?);c+=1;let l=u16le(b,&mut c)? as usize;let e=c.checked_add(l).ok_or(IndexError::Truncated)?;let name=std::str::from_utf8(b.get(c..e).ok_or(IndexError::Truncated)?).map_err(|_|IndexError::InvalidUtf8)?.to_owned();c=e;let e=c.checked_add(dim).ok_or(IndexError::Truncated)?;let vector=b.get(c..e).ok_or(IndexError::Truncated)?.iter().map(|x|*x as i8).collect();c=e;items.push(QuantizedItem{id,name,media_type:mt,vector});}if c!=b.len(){return Err(IndexError::TrailingBytes)}Ok(Self{dimensions:dim,items,positions:pos})}
pub fn len(&self)->usize{self.items.len()}pub fn dimensions(&self)->usize{self.dimensions}fn item(&self,id:&str)->Option<&QuantizedItem>{self.positions.get(id).and_then(|i|self.items.get(*i))}
pub fn recommendations(&self,id:&str,candidate_limit:usize,result_limit:usize,relevance_weight:f32)->Vec<RecommendationHit>{let Some(q)=self.item(id)else{return vec![]};let mut candidates:Vec<(usize,f32)>=self.items.iter().enumerate().filter(|(_,x)|x.id!=id).map(|(i,x)|(i,cos(&q.vector,&x.vector))).collect();candidates.sort_by(|a,b|b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));candidates.truncate(candidate_limit.max(result_limit));let lambda=relevance_weight.clamp(0.0,1.0);let mut selected:Vec<(usize,f32)>=vec![];while !candidates.is_empty()&&selected.len()<result_limit{let(mut bi,mut bs)=(0,f32::NEG_INFINITY);for(i,(idx,rel))in candidates.iter().enumerate(){let red=selected.iter().map(|(s,_)|cos(&self.items[*idx].vector,&self.items[*s].vector).max(0.0)).fold(0.0,f32::max);let score=lambda**rel-(1.0-lambda)*red;if score>bs{bs=score;bi=i}}selected.push(candidates.remove(bi));}selected.into_iter().map(|(i,score)|{let x=&self.items[i];RecommendationHit{id:x.id.clone(),name:x.name.clone(),media_type:x.media_type,score}}).collect()}
}
